# Generated by Django 3.2.5 on 2021-07-25 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_page_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stalker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='stalker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stalker'),
        ),
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.type'),
        ),
    ]
