# Generated by Django 3.2.5 on 2021-07-26 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_history_historytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='url',
        ),
        migrations.AddField(
            model_name='history',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.page'),
        ),
        migrations.AddField(
            model_name='history',
            name='info_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='history',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.historytype'),
        ),
        migrations.AlterField(
            model_name='page',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='stalker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.stalker'),
        ),
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.type'),
        ),
    ]
