# Generated by Django 3.2.5 on 2021-07-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210726_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytype',
            name='descr',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
